# Generated by Django 3.2.9 on 2021-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20211123_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
