# Generated by Django 3.2.9 on 2021-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20211127_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Ссылка картинки'),
            preserve_default=False,
        ),
    ]
